name: Python Linting

on:
  push:
  pull_request:

jobs:
  build:
    name: Python Linting
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install Python Deps
      run: python3 -m pip install ruff

    - name: Lint PicoVision Examples
      shell: bash
      run: |
        python3 -m ruff --show-source --ignore E501 examples/

    - name: Lint PicoVision Python Libraries
      shell: bash
      run: |
        python3 -m ruff --show-source --ignore E501,F401,F403 lib/
